CREATE DATABASE ExploradorAlfa ;
USE ExploradorAlfa ;

CREATE TABLE REGRA (
idREGRA INT NOT NULL PRIMARY KEY,
descricao VARCHAR(120) NULL
 ) ENGINE = InnoDB;


CREATE TABLE HABILIDADE (
idHABILIDADE INT NOT NULL PRIMARY KEY,
h_capacete VARCHAR(45) NULL,
h_blusa VARCHAR(45) NULL,
h_calca VARCHAR(45) NULL,
h_bota VARCHAR(45) NULL
) ENGINE = InnoDB;

CREATE TABLE TRAJE(
idTRAJE INT NOT NULL PRIMARY KEY,
capacete VARCHAR(45) NULL,
blusa VARCHAR(45) NULL,
calca VARCHAR(45) NULL,
bota VARCHAR(45) NULL,
HABILIDADE_idHABILIDADE INT NOT NULL,
FOREIGN KEY (HABILIDADE_idHABILIDADE) REFERENCES HABILIDADE(idHABILIDADE)
) ENGINE = InnoDB;

CREATE TABLE AVATAR (
idAVATAR INT NOT NULL PRIMARY KEY,
aparencia VARCHAR(120) NULL,
TRAJE_idTRAJE INT NOT NULL,
FOREIGN KEY (TRAJE_idTRAJE) REFERENCES TRAJE(idTRAJE)
) ENGINE = InnoDB;

CREATE TABLE JOGADOR (
idJOGADOR INT NOT NULL PRIMARY KEY,
idade INT NOT NULL,
pts_acumulados INT NULL,
email VARCHAR(80) NULL,
senha VARCHAR(45) NULL,
AVATAR_idAVATAR INT NOT NULL,
AVATAR_TRAJE_idTRAJE INT NOT NULL,
FOREIGN KEY (AVATAR_idAVATAR) REFERENCES AVATAR(idAVATAR),
FOREIGN KEY (AVATAR_TRAJE_idTRAJE) REFERENCES AVATAR(TRAJE_idTRAJE)
) ENGINE = InnoDB;

CREATE TABLE NIVEL (
idNIVEL INT NOT NULL PRIMARY KEY,
pontuacao INT NULL,
c_etaria VARCHAR(45) NULL
) ENGINE = InnoDB;

CREATE TABLE NIVEL_has_JOGADOR (
NIVEL_idNIVEL INT NOT NULL,
JOGADOR_idJOGADOR INT NOT NULL,
JOGADOR_AVATAR_idAVATAR INT NOT NULL,
JOGADOR_AVATAR_TRAJE_idTRAJE INT NOT NULL,
FOREIGN KEY (NIVEL_idNIVEL) REFERENCES NIVEL(idNIVEL),
FOREIGN KEY (JOGADOR_idJOGADOR) REFERENCES JOGADOR(idJOGADOR),
FOREIGN KEY (JOGADOR_AVATAR_idAVATAR) REFERENCES JOGADOR(AVATAR_idAVATAR),
FOREIGN KEY (JOGADOR_AVATAR_TRAJE_idTRAJE) REFERENCES JOGADOR(AVATAR_TRAJE_idTRAJE)
) ENGINE = InnoDB;

CREATE TABLE DESAFIOS (
idDESAFIOS INT NOT NULL PRIMARY KEY,
acessorio VARCHAR(45) NULL,
situacao CHAR(1) NULL,
NIVEL_idNIVEL INT NOT NULL,
FOREIGN KEY (NIVEL_idNIVEL) REFERENCES NIVEL(idNIVEL)
) ENGINE = InnoDB;