USE CLASSICMODELS;

/*
Identifique quais produtos por escritório (city) que tiveram mais vendas nos três primeiros meses de 2003
*/

SELECT 
    OFFICES.CITY AS ESCRITORIO,
    PRODUCTNAME AS PRODUTO,
    SUM(QUANTITYORDERED) AS QTD
FROM 
    PRODUCTS
    INNER JOIN ORDERDETAILS USING (PRODUCTCODE)
    INNER JOIN ORDERS USING (ORDERNUMBER)
    INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
    INNER JOIN PAYMENTS USING (CUSTOMERNUMBER)
    INNER JOIN EMPLOYEES ON SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER
    INNER JOIN OFFICES USING (OFFICECODE)
WHERE 
    MONTH(PAYMENTDATE) IN (1, 2, 3)
    AND YEAR(PAYMENTDATE) = 2003
GROUP BY 
    OFFICES.CITY, PRODUCTNAME
ORDER BY 
    QTD DESC;
    
USE SAKILA;

/*
Identifique o idioma e a categoria dos filmes mais alugados, mostrando a quantidade alugada e o valor acumulado.
Você deve mostrar em seu resultado o idioma, a categoria e as demais informações solicitadas.
*/

SELECT 
    LANGUAGE.NAME AS IDIOMA,
    CATEGORY.NAME AS CATEGORIA,
    COUNT(RENTAL_ID) AS QTDE_ALUGADA,
    SUM(AMOUNT) AS VALOR_ACUMULADO
FROM 
    CATEGORY
    INNER JOIN FILM_CATEGORY USING (CATEGORY_ID)
    INNER JOIN FILM USING (FILM_ID)
    INNER JOIN LANGUAGE USING (LANGUAGE_ID)
    INNER JOIN INVENTORY USING (FILM_ID)
    INNER JOIN RENTAL USING (INVENTORY_ID)
    INNER JOIN PAYMENT USING (RENTAL_ID)
WHERE 
    YEAR(PAYMENT_DATE) = 2005
GROUP BY 
    IDIOMA, CATEGORIA;
    
-- UTILIZANDO O CASE
SELECT 
    CONCAT(FIRSTNAME, ' ', LASTNAME) AS VENDEDOR,
    SUM(AMOUNT) AS TOTAL_VENDIDO,
    CASE 
        WHEN SUM(AMOUNT) > CREDITLIMIT THEN 'CONVERSAR COM O CLIENTE'
        ELSE 'AUMENTAR O VALOR DE CRÉDITO'
    END AS SITUACAO
FROM 
    PAYMENTS
    INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
    INNER JOIN EMPLOYEES ON SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER
WHERE 
    YEAR(PAYMENTDATE) = 2004
    AND MONTH(PAYMENTDATE) IN (4, 5, 6)
GROUP BY 
    VENDEDOR;